import type { Player, LineupSize, SplitCycle } from '../types';

export type ScoreEventLike = {
  team: 1 | 2;
  pointNumber: number;
};

export function formatRatio(men: number, women: number): string {
  return `${men}:${women}`;
}

export function buildScoreReport(params: {
  team1Name: string;
  team2Name: string;
  team1Score: number;
  team2Score: number;
  pointNumber: number;
  lineupSize: LineupSize;
  startingOpen: number;
  splitCycle: SplitCycle;
  roster: Player[];
  masterOpenQueue: Player[];
  masterWomenQueue: Player[];
  currentLine: Player[];
  scoreHistory: ScoreEventLike[];
  generatedAt?: Date;
}): string {
  const now = params.generatedAt ?? new Date();
  const timestamp = now.toLocaleString();
  const gameDate = now.toLocaleDateString();
  const pointLog = params.scoreHistory.length
    ? params.scoreHistory
        .map((e) => `  Point ${e.pointNumber}: ${e.team === 1 ? params.team1Name : params.team2Name}`)
        .join('\n')
    : '  (no points yet)';

  const line = params.currentLine.length
    ? params.currentLine.map((p) => p.name).join(', ')
    : '(none)';

  return `Ultimate Frisbee Score Report
Generated: ${timestamp}
Game Date: ${gameDate}

SCORE:
${params.team1Name} ${params.team1Score} – ${params.team2Score} ${params.team2Name}

POINT LOG:
${pointLog}

CURRENT LINE:
${line}

FULL ROSTER (${params.roster.length} players):
${params.roster.map((player, index) => `${index + 1}. ${player.name} (${player.gender === 'O' ? 'Open' : 'Women'}) - #${player.number}`).join('\n') || '(empty)'}

ROTATION ORDER (Open):
${params.masterOpenQueue.length ? params.masterOpenQueue.map((p, i) => `${i + 1}. ${p.name}`).join('\n') : '(none)'}

ROTATION ORDER (Women):
${params.masterWomenQueue.length ? params.masterWomenQueue.map((p, i) => `${i + 1}. ${p.name}`).join('\n') : '(none)'}

SETTINGS:
Players per point: ${params.lineupSize}
Starting split: ${formatRatio(params.startingOpen, params.lineupSize - params.startingOpen)}
Cycle: ${params.splitCycle}

---
Report generated by Ultimate Score App
`;
}

export function scoreShareTitle(team1Name: string, team2Name: string, s1: number, s2: number): string {
  return `${team1Name} ${s1}–${s2} ${team2Name}`;
}

export function whatsAppShareUrl(text: string): string {
  return `https://wa.me/?text=${encodeURIComponent(text)}`;
}

export function mailtoShareUrl(subject: string, body: string): string {
  return `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

export function downloadTextFile(filename: string, text: string): void {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
