import type { Player, LineupSize, SplitCycle } from '../types';
import type { SoftPointCap } from './softCap';
import { formatSoftCap } from './softCap';

export type ScoreEventLike = {
  team: 1 | 2;
  pointNumber: number;
  linePlayerIds?: string[];
};

export function formatRatio(men: number, women: number): string {
  return `${men}:${women}`;
}

export function tallyPointsPlayed(
  roster: Player[],
  scoreHistory: ScoreEventLike[]
): { name: string; gender: 'O' | 'W'; points: number }[] {
  const counts = new Map<string, number>();
  for (const event of scoreHistory) {
    for (const id of event.linePlayerIds ?? []) {
      counts.set(id, (counts.get(id) ?? 0) + 1);
    }
  }
  return roster
    .map((p) => ({
      name: p.name,
      gender: p.gender,
      points: counts.get(p.uuid) ?? 0,
    }))
    .sort((a, b) => b.points - a.points || a.name.localeCompare(b.name));
}

export function buildScoreReport(params: {
  team1Name: string;
  team2Name: string;
  team1Score: number;
  team2Score: number;
  pointNumber: number;
  lineupSize: LineupSize;
  startingOpen: number;
  splitCycle: SplitCycle;
  softCap?: SoftPointCap;
  roster: Player[];
  masterOpenQueue: Player[];
  masterWomenQueue: Player[];
  currentLine: Player[];
  scoreHistory: ScoreEventLike[];
  generatedAt?: Date;
}): string {
  const now = params.generatedAt ?? new Date();
  const timestamp = now.toLocaleString();
  const gameDate = now.toLocaleDateString();
  const pointLog = params.scoreHistory.length
    ? params.scoreHistory
        .map((e) => `  Point ${e.pointNumber}: ${e.team === 1 ? params.team1Name : params.team2Name}`)
        .join('\n')
    : '  (no points yet)';

  const line = params.currentLine.length
    ? params.currentLine.map((p) => p.name).join(', ')
    : '(none)';

  const played = tallyPointsPlayed(params.roster, params.scoreHistory);
  const playedBlock = played.length
    ? played
        .map(
          (p) =>
            `  ${p.name} (${p.gender === 'O' ? 'Open' : 'Women'}): ${p.points}`
        )
        .join('\n')
    : '  (none)';

  return `Ultimate Frisbee Score Report
Generated: ${timestamp}
Game Date: ${gameDate}

SCORE:
${params.team1Name} ${params.team1Score} – ${params.team2Score} ${params.team2Name}

POINT LOG:
${pointLog}

CURRENT LINE:
${line}

POINTS PLAYED:
${playedBlock}

FULL ROSTER (${params.roster.length} players):
${params.roster.map((player, index) => `${index + 1}. ${player.name} (${player.gender === 'O' ? 'Open' : 'Women'}) - #${player.number}`).join('\n') || '(empty)'}

ROTATION ORDER (Open):
${params.masterOpenQueue.length ? params.masterOpenQueue.map((p, i) => `${i + 1}. ${p.name}`).join('\n') : '(none)'}

ROTATION ORDER (Women):
${params.masterWomenQueue.length ? params.masterWomenQueue.map((p, i) => `${i + 1}. ${p.name}`).join('\n') : '(none)'}

SETTINGS:
Players per point: ${params.lineupSize}
Starting split: ${formatRatio(params.startingOpen, params.lineupSize - params.startingOpen)}
Cycle: ${params.splitCycle}
Soft point cap: ${formatSoftCap(params.softCap ?? null)}

---
Report generated by Ultimate Score App
`;
}

export function scoreShareTitle(team1Name: string, team2Name: string, s1: number, s2: number): string {
  return `${team1Name} ${s1}–${s2} ${team2Name}`;
}

export function downloadTextFile(filename: string, text: string): void {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
